const isValidCommitMessage = (message): boolean => {
    // Exceptions.
    // This is a message that's auto-generated by git. Can't do much about it unfortunately. Let's allow it.
    if (message.startsWith("Merge ") || message.startsWith("Revert ")) {
        return true;
    }

    let pattern = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: \S+([\s\S]*)/
    return pattern.test(message)
};

export default isValidCommitMessage;
